### PR TITLE
ChatBot feature done

### LINKED ISSUE #13: [FEATURE] Chatbot UI Design (Base Features)
**Chatbot UIs.**
These are the UIs for the chatbot feature. It involves all the possible usages of the chatbot. I.e User Onboarding, Incident report, e.t.c

### PR DESCRIPTION
**Pull request by Vheeck**
## Description
The chatbot feature of the app was implemented. Dialogflow was used.
Dependencies include: 
- react-native-tts
- react-native-dialogflow
- @react-native-community/voice
- react-native-vector-icons

All pull requests should be related to open issues. Indicate the issue(s) bellow and remove this line:
Fixes #13 #14 

## How Has This Been Tested?
The feature has been tested on a physical device and on an android emulator. The app could not be tested for IOS because my development machine is windows and can't debug for IOS.

## Screenshots (if applicable, else remove this line / section)
Screenshot_20200528-092929
Screenshot_20200528-092934
Screenshot_20200528-092938

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Leoactionz — APPROVED** [review]
the bot is quite interactive

**Comment by chimeziesolomon** [comment]
reviewed

**Comment by chimeziesolomon** [comment]
good one

**Review by chimeziesolomon — APPROVED** [review]
nice feature

**Pull request merged**
